_security_logout:
    resource: security.route_loader.logout
    type: service

# firewalls:
#     main:
#         # ...
#         form_login:
#             # "app_login" is the name of the route created previously
#             login_path: app_login
#             check_path: app_login